"use server";

import prisma from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export interface ProductVariantInput {
  material_id: string;
  size_id: string;
  thickness_id: string;
  price: number;
  compare_at_price?: number | null;
  cost_per_item?: number | null;
  is_default?: boolean;
}

export interface ProductImageInput {
  storage_path: string;
  thumbnail_path?: string | null;
  medium_path?: string | null;
  large_path?: string | null;
  display_order: number;
  blurhash?: string | null;
  alt_text?: string | null;
  processing_status?: string;
  is_primary?: boolean;
}

export interface CreateProductInput {
  name: string;
  description: string;
  category_id?: string | null;
  status: "draft" | "active" | "archived";
  is_featured: boolean;
  seo_title?: string | null;
  seo_description?: string | null;
  variants: ProductVariantInput[];
  images: ProductImageInput[];
}

export interface UpdateProductInput extends CreateProductInput {
  id: string;
}

export async function createProduct(input: CreateProductInput) {
  try {
    // Validate that we have at least one image
    if (!input.images || input.images.length === 0) {
      return {
        success: false,
        error: "Please upload at least one product image",
      };
    }

    // Validate that we have at least one variant
    if (!input.variants || input.variants.length === 0) {
      return {
        success: false,
        error: "Add at least one variant",
      };
    }

    // Create product with variants and images in a single transaction using Prisma deep insertion
    const product = await prisma.products.create({
      data: {
        name: input.name,
        description: input.description || null,
        category_id: input.category_id || null,
        status: input.status,
        is_featured: input.is_featured,
        seo_title: input.seo_title || null,
        seo_description: input.seo_description || null,
        // Deep insertion: Create all variants with the product
        product_variants: {
          create: input.variants.map((variant) => ({
            material_id: variant.material_id,
            size_id: variant.size_id,
            thickness_id: variant.thickness_id,
            price: variant.price,
            compare_at_price: variant.compare_at_price || null,
            cost_per_item: variant.cost_per_item || null,
            is_default: variant.is_default || false,
            sku: "", // SKU will be auto-generated by database trigger
          })),
        },
        // Deep insertion: Create images with the product
        product_images: {
          create: input.images.map((image) => ({
            storage_path: image.storage_path,
            thumbnail_path: image.thumbnail_path || null,
            medium_path: image.medium_path || null,
            large_path: image.large_path || null,
            display_order: image.display_order,
            blurhash: image.blurhash || null,
            alt_text: image.alt_text || null,
            processing_status: image.processing_status || "completed",
            is_primary: image.is_primary || false,
          })),
        },
      },
      include: {
        product_variants: true,
        product_images: true,
      },
    });

    // Convert Decimal fields to numbers for client serialization
    const serializedProduct = {
      ...product,
      product_variants: product.product_variants.map((variant) => ({
        ...variant,
        price: Number(variant.price),
        compare_at_price: variant.compare_at_price ? Number(variant.compare_at_price) : null,
        cost_per_item: variant.cost_per_item ? Number(variant.cost_per_item) : null,
      })),
    };

    // Revalidate the products page
    revalidatePath("/admin/products");

    return {
      success: true,
      data: serializedProduct,
    };
  } catch (error: any) {
    console.error("Error in createProduct:", error);
    return {
      success: false,
      error: error.message || "An unexpected error occurred",
    };
  }
}

export async function updateProduct(input: UpdateProductInput) {
  try {
    console.log("Updating product with ID:", input.id);

    // Validate that we have at least one image
    if (!input.images || input.images.length === 0) {
      return {
        success: false,
        error: "Please upload at least one product image",
      };
    }

    // Validate that we have at least one variant
    if (!input.variants || input.variants.length === 0) {
      return {
        success: false,
        error: "Add at least one variant",
      };
    }

    // Update product with nested variant and image replacement using Prisma
    const product = await prisma.products.update({
      where: {
        id: input.id,
      },
      data: {
        name: input.name,
        description: input.description || null,
        category_id: input.category_id || null,
        status: input.status,
        is_featured: input.is_featured,
        seo_title: input.seo_title || null,
        seo_description: input.seo_description || null,
        // Replace all variants: delete existing and create new ones
        product_variants: {
          deleteMany: {}, // Delete all existing variants
          create: input.variants.map((variant) => ({
            material_id: variant.material_id,
            size_id: variant.size_id,
            thickness_id: variant.thickness_id,
            price: variant.price,
            compare_at_price: variant.compare_at_price || null,
            cost_per_item: variant.cost_per_item || null,
            is_default: variant.is_default || false,
            sku: "", // SKU will be auto-generated by database trigger
          })),
        },
        // Replace all images: delete existing and create new ones
        product_images: {
          deleteMany: {}, // Delete all existing images
          create: input.images.map((image) => ({
            storage_path: image.storage_path,
            thumbnail_path: image.thumbnail_path || null,
            medium_path: image.medium_path || null,
            large_path: image.large_path || null,
            display_order: image.display_order,
            blurhash: image.blurhash || null,
            alt_text: image.alt_text || null,
            processing_status: "pending",
            is_primary: image.is_primary || false,
          })),
        },
      },
      include: {
        product_variants: true,
        product_images: true,
      },
    });

    console.log("Product updated successfully:", product.id);

    // Convert Decimal fields to numbers for client serialization
    const serializedProduct = {
      ...product,
      product_variants: product.product_variants.map((variant) => ({
        ...variant,
        price: Number(variant.price),
        compare_at_price: variant.compare_at_price ? Number(variant.compare_at_price) : null,
        cost_per_item: variant.cost_per_item ? Number(variant.cost_per_item) : null,
      })),
    };

    // Revalidate the products page
    revalidatePath("/admin/products");
    revalidatePath(`/admin/products/${input.id}`);

    return {
      success: true,
      data: serializedProduct,
    };
  } catch (error: any) {
    console.error("Error in updateProduct:", error);

    // Handle specific Prisma errors
    if (error.code === "P2025") {
      return {
        success: false,
        error: `Product with ID ${input.id} not found`,
      };
    }

    return {
      success: false,
      error: error.message || "An unexpected error occurred",
    };
  }
}
